site_name: DicasDeEstagio - G5
#site_author: Mateus Villela
site_description: Site voltado para a documentação do Grupo 5 de Arquitetura e Desenvolvimento de Software - 2025.2
repo_url: https://github.com/UnBArqDsw2025-2-Turma02/2025.2-T02_G5_DicasDeEstagio_Entrega02
repo_name: 2025.2-DicasDeEstagio-Entrega02

theme:
  name: material
  logo: 'assets/imgs/outros/entrega1/LogoPrincipalG5.png'
  favicon: 'assets/imgs/outros/entrega1/LogoPrincipalG5.png'

  palette:
    - scheme: default
      primary: "#1A2B45"   # Azul escuro 
      accent: "#00A86B"    # Verde 
      auxiliary: "#36A9E1" # Azul claro 
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      primary: "#1A2B45"   # Azul escuro
      accent: "#00A86B"    # Verde
      auxiliary: "#36A9E1" # Azul claro
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Início: index.md
  - 2. Desenho de Software (Modelagem):
    - 2.1. Introdução: Modelagem/index_modelagem.md
    - 2.2. UML Estático:
      - 2.2.1. Visão Geral: Modelagem/estatica_uml/modelagem_estatica.md
      - 2.2.2. Diagrama de Classes: Modelagem/estatica_uml/diagrama_classes.md
      - 2.2.3. Diagrama de Implementação: Modelagem/estatica_uml/diagrama_implementacao.md
    - 2.3. UML Dinâmico:
      - 2.3.1. Visão Geral: Modelagem/dinamica_uml/modelagem_dinamica.md
      - 2.3.2. Diagrama de Estados: Modelagem/dinamica_uml/diagrama_estados.md
      - 2.3.3. Diagrama de Atividades: Modelagem/dinamica_uml/diagrama_atividades.md
    - 2.4. UML Organizacional:
      - 2.4.1. Visão Geral: Modelagem/organizacional_uml/modelagem_organizacional.md
      - 2.4.2. Diagrama de Casos de Uso: Modelagem/organizacional_uml/diagrama_casos_uso.md
    - 2.5. Iniciativas Extras:
      - 2.5.1. Índice: iniciativas_extras/index_iniciativas.md
      - 2.5.2. Backlog do Produto: iniciativas_extras/Backlog/backlog.md
      - 2.5.3. Planejamento:
        - Ferramentas: iniciativas_extras/Planejamento/Ferramentas.md
        - Heatmap Disponibilidade: iniciativas_extras/Planejamento/HeatmapDisponibilidade.md
        - Políticas de Repositório:
          - Política de Branches: iniciativas_extras/Planejamento/Politicas-de-repositorio/PoliticaBranches.md
          - Política de Commits: iniciativas_extras/Planejamento/Politicas-de-repositorio/PoliticaCommits.md
      - 2.5.4. Incremento de Elicitação:
        - Questionário: iniciativas_extras/incremento_elicitacao/questionario.md
        - Tabela Geral de Requisitos: iniciativas_extras/incremento_elicitacao/tabela_geral_requisitos.md
    - 2.6. Participações: participacoes.md
    - 2.7. Reuniões - Atas:
      - Ata 1 - 24/08/2025: iniciativas_extras/Planejamento/atas/ata1.md
      - Ata 2 - 27/08/2025: iniciativas_extras/Planejamento/atas/ata2.md
      - Ata 3 - 02/09/2025: iniciativas_extras/Planejamento/atas/ata3.md
      - Ata 4 - 10/09/2025: iniciativas_extras/Planejamento/atas/ata4.md
      - Ata 5 - 17/09/2025: iniciativas_extras/Planejamento/atas/ata5.md

markdown_extensions:
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mkdocs-pdf

extra_css:
  - assets/css/custom.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js